include:
  - docker-compose-common.yml

services:

  augmentoolkit:
    container_name: augmentoolkit
    hostname: augmentoolkit
    user: root
    depends_on:
      - redis
    profiles:
      - augmentoolkit
    restart: unless-stopped
    build:
      context: ./docker/augmentoolkit
      dockerfile: dockerfile.augmentoolkit
    volumes:
    - augmentoolkit:/app/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=3
    ports:
    - "127.0.0.1:8000:8000" # api
    - "127.0.0.1:5173:5173" # ui
    - "127.0.0.1:8083:8082" # vllm
    devices:
      - nvidia.com/gpu=all
      - /dev/video0

volumes:
  augmentoolkit:
