include:
 - docker-compose-common.yml
 - docker-compose-openwebui.yml

services:
  langflow:
    container_name: langflow
    hostname: langflow
    profiles:
      - langflow
    image: docker.io/langflowai/langflow:latest
    #pull_policy: always
    restart: unless-stopped
    ports:
      - "127.0.0.1:7860:7860"
    depends_on:
      - postgres-langflow
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres-langflow:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=/app/langflow
      - DO_NOT_TRACK=true
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_DB=4
      - LANGFLOW_REDIS_HOST=redis

    volumes:
      - langflow-data:/app/langflow

  postgres-langflow:
    container_name: postgres-langflow
    hostname: postgres-langflow
    profiles:
      - langflow
    image: postgres:16
    #pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    # ports:
    #   - "127.0.0.1:5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
