include:
  - docker-compose-langflow.yml
  - docker-compose-n8n.yml
  - docker-compose-openwebui.yml
  - docker-compose-ollama.yml
  - docker-compose-comfyui.yml
  - docker-compose-facefusion.yml
  - docker-compose-facefusion-webcam.yml
  - docker-compose-augmentoolkit.yml
  - docker-compose-vllm.yml
  - docker-compose-nvidia.yml
  - docker-compose-unsloth.yml
  - docker-compose-mcp.yml
