# Base image with Python 3.11 and CUDA 12.5 support
FROM docker.io/nvidia/cuda:12.8.0-runtime-ubuntu24.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    vim \
    libgl1 \
    python3-pip \
    python3-venv \
    libglx-mesa0 \
    libglib2.0-0 \
    ffmpeg
# Set working directory
WORKDIR /

# Copy the cloned ComfyUI repository
RUN git clone --depth 1 https://github.com/comfyanonymous/ComfyUI.git /app

WORKDIR /app

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose the port used by ComfyUI
EXPOSE 8188

COPY src/entrypoint.sh /

RUN chmod +x /entrypoint.sh

CMD /entrypoint.sh

